postgres:
  image: postgres:9.6
  environment:
    POSTGRES_USER:
    POSTGRES_PASSWORD:
  ports:
    - '5432:5432'
  volumes:
    - numa-postgres:/var/lib/postgresql/data

redis:
  image: redis:3.0.5
  ports:
    - '6379:6379'
  volumes:
    - numa-redis:/var/lib/redis/data

app:
  build: .
  command: rails server -p 3000 -b '0.0.0.0'
  links:
    - postgres
    - redis
  volumes:
    - .:/numa
  ports:
    - '3000:3000'
  env_file:
    - .env

sidekiq:
  build: .
  command: bundle exec sidekiq -C config/sidekiq.yml
  links:
    - postgres
    - redis
  volumes:
    - .:/numa
  env_file:
    - .env

docker:
  image: trufflesuite/ganache-cli
  ports:
    - '8500:8545'
  command: --account 0xb5b93f2bcd2e15081a55d9742a40a661aa8d756c37770aff33470e25e81d4603,1e24